//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Infrastructure.Data.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Nomes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Nomes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Infrastructure.Data.Resource.Nomes", typeof(Nomes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agravo.
        /// </summary>
        public static string Agravo {
            get {
                return ResourceManager.GetString("Agravo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        public static string Arquivo {
            get {
                return ResourceManager.GetString("Arquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certidão de Óbito.
        /// </summary>
        public static string CertidaoObito {
            get {
                return ResourceManager.GetString("CertidaoObito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competência.
        /// </summary>
        public static string Competencia {
            get {
                return ResourceManager.GetString("Competencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunicado.
        /// </summary>
        public static string Comunicado {
            get {
                return ResourceManager.GetString("Comunicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embargo de Declaração.
        /// </summary>
        public static string EmbargoDeclaracao {
            get {
                return ResourceManager.GetString("EmbargoDeclaracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Município.
        /// </summary>
        public static string Municipio {
            get {
                return ResourceManager.GetString("Municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natureza.
        /// </summary>
        public static string Natureza {
            get {
                return ResourceManager.GetString("Natureza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofício.
        /// </summary>
        public static string Oficio {
            get {
                return ResourceManager.GetString("Oficio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parte.
        /// </summary>
        public static string Parte {
            get {
                return ResourceManager.GetString("Parte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido de Reexame.
        /// </summary>
        public static string PedidoReexame {
            get {
                return ResourceManager.GetString("PedidoReexame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petição.
        /// </summary>
        public static string Peticao {
            get {
                return ResourceManager.GetString("Peticao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string Processo {
            get {
                return ResourceManager.GetString("Processo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurso Ordinário.
        /// </summary>
        public static string RecursoOrdinario {
            get {
                return ResourceManager.GetString("RecursoOrdinario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relator.
        /// </summary>
        public static string Relator {
            get {
                return ResourceManager.GetString("Relator", resourceCulture);
            }
        }
    }
}
